feature: add auth/dynamic get user position
yenting-biao/FoodDate pull request #33
Opened 2023-12-26 15:00 UTC by nukkk97

If we need email verification, we may need two more data for each user in database: isVerified and randomToken.
The time isn't that much so I'm considering if we should still implement it. For now, the basic auth without email verification is done.
Also, in "/restaurants", I change the original getPosition() api to watchPosition(), which allows us to dynamically get user's location. Now if you are walking, you should notice that the marker is also moving.

2023-12-26 15:12 UTC, yenting-biao commented
The time isn't that much so I'm considering if we should still implement it. For now, the basic auth without email verification is done.
-> ok, we can do this in the future if we have time

2023-12-26 15:13 UTC, yenting-biao commented on public/map-and-location.png
這是什麼

2023-12-26 15:17 UTC, yenting-biao approved these changes

2023-12-26 15:20 UTC, nukkk97 commented on public/map-and-location.png
A great image.

2023-12-26 15:21 UTC, nukkk97 commented
Note that in Header.tsx,148: <AuthForm onCloseAuthModal={handleCloseAuthModal} />
Still need to be modified since I discard the modal props.

2023-12-27 05:49 UTC, togimoto requested changes

2023-12-27 05:49 UTC, togimoto commented on src/app/_components/AuthForm.tsx
> +                 {!!props.error&&<p className="bg-red-100 text-red-600 text-center p-2">帳號或密碼錯誤，請重試！</p>}
為什麼有兩個驚嘆號？

2023-12-27 05:53 UTC, nukkk97 commented on src/app/_components/AuthForm.tsx
> +                 {!!props.error&&<p className="bg-red-100 text-red-600 text-center p-2">帳號或密碼錯誤，請重試！</p>}
It is just a safe way to convert to boolean

2023-12-27 05:56 UTC, togimoto approved these changes
Thanks!

2023-12-27 05:56 UTC, merged